language: php

php:
#  - 7.1
#  - 7.2
#  - 7.3
  - 7.4

dist: trusty

env:
  - CAKEPHP_VERSION=4.0.*

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer require "cakephp/cakephp:${CAKEPHP_VERSION}" --no-update

install: composer update --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email: true
